### ISSUE TITLE
FPV Armed but rotors not spinning

### ISSUE THREAD

**Issue by olouherv** [darkterbear/drone#1]
Thank you for your tutorial on [your website](https://terranceli.com/blog/building-a-drone/).
I have a fpv with mamba stack. 
I follow each step according to your tutorial.
test-fc-telemetry.py works but when I run the test-fc-command.py the fpv armed but not the rotors not spinning.

**Comment by omirbod** [comment]
Hello, I was wondering if you were able to solve that problem, I am having the same issue. It seems like it's armed but the motors do not spin. They do spin if I use betaflight to manually spin them.
